paths:
  base_path: /g100_work/ARPAE_AQM/MIMESI/
  env_python: miniconda3/bin/python3.13

  listing_file: DART/observations/obs_converters/S5P_TROPOMI_L3/data/SO2-COBRA/C03__listing.csv
  run_submit_model_template: catena_aria_test/Chimere/run_mimesi-ITA7_template.sh
  path_submit_bsh: catena_aria_test/Chimere/auto_runs
  path_filter: DART/models/CHIMERE_v2017r/work_offline
  path_data: runs_chimere/ITA7
  run_submit_replace_perturbations: DART/mimesi_orch/perturbation/bash_emissions/submit_replace_perturb_into_original_emission_arg.sh
  log_directory: logs_orchestrator


time:
  start_time: "2026-01-25 00:00:00"
  end_time: "2026-01-26 01:00:00"
  dt_seconds: 3600

  backup_perturb_days: 2
  backup_ic_hours: 48
  backup_ic_option: hourly


assimilation:
  run_assimilation_flag: false
  model_type: CHIMERE
  ass_var: c_NO2
  state_variable_qty: QTY_NO2
  obs_type: SAT_NO2_TROPOMI

  case_dir: data_freerun
  case_emi_dir: emi
  emi_var: NO2
  no_mems: 2


cluster:
  cluster_queue: g100_usr_prod
  scheduler : SLURM


dart:
  work_dir: DART/models/FARM/work_freerun
  analysis_dir: RUN/data_freerun/analysis
  preassim_dir: RUN/data_freerun/preassim
  posteriors_dir: RUN/data_freerun/posteriors
  obs_converters_dir: DART/observations/obs_converters/S5P_TROPOMI_L3


logging:
  level: INFO
  format: "%(asctime)s [%(processName)s/%(threadName)s] %(levelname)s: %(message)s"


satellite_data:
  search_window_seconds: 1800

runtime:
  profile: mimesi
  log_dir_mode: path_data
  log_dir_name: mimesi_orchestrator_logs
